### ISSUE TITLE
Improve output if clone fails

### ISSUE THREAD

**Issue by timwebster9** [buildit/jenkins-config-fetcher#1]
If the initial `git clone` of the config fails, there is no way to tell what happened.  All you see is the exit code, usually 128.

```
jenkins_1  | executing command: git  clone -b master https://github.com/buildit/jenkins-config.git /tmp/3c6c68e8-19c4-4e18-b8d8-d54904277135
jenkins_1  | exit value: 128
jenkins_1  | Caught: java.lang.RuntimeException: Process exited with non-zero value: 128
jenkins_1  | java.lang.RuntimeException: Process exited with non-zero value: 128
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.execute(ConfigFetcher.groovy:301)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.execute(ConfigFetcher.groovy:286)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.checkout(ConfigFetcher.groovy:182)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher$_listFiles_closure5.doCall(ConfigFetcher.groovy:155)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.listFiles(ConfigFetcher.groovy:153)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher$listFiles$2.callCurrent(Unknown Source)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.configStrings(ConfigFetcher.groovy:80)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.getConfig(ConfigFetcher.groovy:64)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher$getConfig$0.callCurrent(Unknown Source)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher.fetch(ConfigFetcher.groovy:16)
jenkins_1  |    at com.buildit.jenkins.configfetcher.ConfigFetcher$fetch.call(Unknown Source)
jenkins_1  |    at main.run(main.groovy:4)
jenkins_1  | Error: Unable to access jarfile exit
jenkins_1  | Arrgg!! Looks like something went wrong. Check you have defined a jenkins version in your config - it's usually that.
```

**Comment by dermotmburke** [comment]
Was thinking of switching to jgit to do the clone. I'm not sure I like presuming the git is going to be available. This would probably yield a nicer error message too.

**Comment by timwebster9** [comment]
Yeah that would probably be nicer if you need to do the clone in Groovy.  Either way think I have a fix.  See https://github.com/buildit/jenkins-config-fetcher/pull/2
